config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meetings do
    resources :attendees, only: [:new, :create, :edit, :update, :destroy]
  end
  # resources :groups

  # get '/users/:username', to: "users#show", as: :user
  get '/dashboard', to: "pages#dashboard"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :meeting

  scope :confirmed, -> { where(confirmed: true) }
  scope :awaiting, -> { where(confirmed: false) }
  scope :declined, -> { where(declined: true) }


end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :attendees, dependent: :destroy
  has_many :users, through: :attendees
  belongs_to :owner, class_name: "User", foreign_key: :owner_id

  # attr_accessor :owner

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?


  def dateFormat
    return date.strftime('%d/%m @ %H:%M')
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :username

  has_many :hosted_meetings, class_name: "Meeting", foreign_key: :owner_id
  has_many :attendees
  has_many :meetings, through: :attendees
  # has_many :memberships
  # has_many :groups, through: :memberships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :find_attendee, only: [:edit, :update, :destroy]

  def new
    @attendee = Attendee.new
    @meeting = Meeting.find(params[:meeting_id])
    authorize @attendee
    respond_to do |format|
      format.js
    end
  end

  def create
    @attendee = Attendee.new(validate_attendee)
    meeting = Meeting.find(params[:meeting_id])
    @attendee.user = current_user
    @attendee.meeting = meeting
    authorize @attendee
    if @attendee.save!
      respond_to do |format|
        format.js { flash.now[:notice] = 'Request sent!' }
      end
    else
      render :new
    end
  end

  def edit; end

  def update
    @received_requests = Attendee.joins(:meeting).where(meetings: {owner_id: current_user}, attendees: {confirmed: false, declined: false})
    @pending_requests = current_user.attendees
    if @attendee.update(validate_attendee)
      authorize @attendee
      respond_to do |format|
        format.js { flash.now[:notice] = 'Response sent!' }
      end
    end
  end

  def destroy
    authorize @attendee
    @attendee.destroy
  end

  private

  def find_attendee
    @attendee = Attendee.find(params[:id])
    authorize @attendee
  end

  def validate_attendee
    params.require(:attendee).permit(:message, :confirmed, :declined)
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_meeting, only: [:show, :edit, :update, :destroy]

  def index
    # @meetings = Meeting.all
    @meetings = policy_scope(Meeting)
  end

  def show
    @current_meeting = current_user.attendees.where(meeting: @meeting)
    data = Geocoder.search("#{@meeting.google_place_id}", lookup: :google, google_place_id: true)
    if !data.empty?
      @marker = [{
        lat: data[0].geometry['location']['lat'],
        lng: data[0].geometry['location']['lng']
      }]
    end
    # attendance = @meeting.attendees.reduce
  end

  def new
    @meeting = Meeting.new
    authorize @meeting
  end

  def create
    @meeting = Meeting.create(validate_meeting)
    @meeting.owner = current_user
    # @meeting.user = current_user
    authorize @meeting
    if @meeting.save!
      flash[:success] = "Meeting created!"
      redirect_to meeting_path(@meeting)
    else
      render :new
    end
  end

  def edit; end

  def update
    @meeting.update(validate_meeting)
    redirect_to meeting_path(@meeting)
    authorize @meeting
  end

  def destroy
    authorize @meeting
    @meeting.destroy
    redirect_to meetings_path
  end

  private

  def find_meeting
    @meeting = Meeting.find(params[:id])
    authorize @meeting
  end

  def validate_meeting
    params.require(:meeting).permit(:title, :description, :date, :location, :google_place_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @meetings = Meeting.geocoded
    @markers = @meetings.map do |meeting|
      data = Geocoder.search("#{meeting.google_place_id}", lookup: :google, google_place_id: true)
      {
        lat: data[0].geometry['location']['lat'],
        lng: data[0].geometry['location']['lng'],
        infoWindow: {
          content: render_to_string(partial: "info_window", locals: { meeting: meeting })
        }
      }
    end
  end

  def dashboard
    @received_requests = Attendee.joins(:meeting).where(meetings: {owner_id: current_user}, attendees: {confirmed: false, declined: false})
    @pending_requests = current_user.attendees.includes(:meeting, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_username(params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendees/_new.html.erb
<div class="container">
  <%= simple_form_for [@meeting, @attendee], remote:true do |f| %>
    <%= f.input :message, label: 'Message the host', input_html: { maxlength: 60, size: 20} %>
    <%= f.button :submit, 'Request to join', class: "form-submit-btn" %>
  <% end %>
</div>

app/views/attendees/create.js.erb
document.getElementById('new-attendance-render').innerHTML = "Sent!";
document.querySelector('.flash-wrapper').innerHTML = '<%= j render '/shared/flashes' %>'
setTimeout(() => {
  document.querySelector('.flash-wrapper').remove();
}, 3000);

app/views/attendees/new.js.erb
document.getElementById('new-attendance-render').innerHTML = "<%= j (render 'new') %>"

app/views/attendees/update.js.erb
// On accept / decline meeting request remove the request from the list and render updated hosting view
document.querySelector('.hosting-render').innerHTML = '<%= j render '/pages/hosting' %>'
document.querySelector('.requested-render').innerHTML = '<%= j render '/pages/requested/' %>'
// document.querySelector('.sent-render').innerHTML = '<%= j render '/pages/sent/' %>'
document.querySelector('.tab-select').innerHTML = '<%= j render '/pages/tabs' %>'
document.querySelector('.flash-wrapper').innerHTML = '<%= j render '/shared/flashes' %>'
setTimeout(() => {
  document.querySelector('.flash-wrapper').innerHTML = "";
}, 3000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worksp_ce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%#= javascript_include_tag "application" %>
    <%= render 'shared/navbar' %>
    <div class="flash-wrapper">
      <%= render 'shared/flashes' %>
    </div>
    <%= yield %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_BROWSER_API_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/meetings/edit.html.erb
<h1>Edit this meeting</h1>

<div class="container">
  <%= simple_form_for @meeting do |f| %>
    <%= f.input :date %>
    <%= f.input :location %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/meetings/index.html.erb
<div id="headline">
  <h1>All meetings</h1>
  <input id="index-search" type="text">
<!--     <table id="resultsTable">
      <tbody id="results"></tbody>
    </table> -->
  <button class="button-wrk">Search</button>
</div>
<div class="index-container">
  <div class="meeting-index-grid">
    <% @meetings.each do |meeting| %>
        <div class="meeting-grid-card">
          <img src="https://e3.365dm.com/18/05/768x432/skynews-world-map-map_4298829.jpg?20180502134213" alt="">
          <p><%= meeting.title %></p>
          <p><%= meeting.location %></p>
          <p><%= meeting.date %></p>
        </div>
    <% end %>
  </div>
  <div class="index-map">
    <div
      id="map"
      style="width: 100%;
      height: 560px;"

    ></div>
  </div>
</div>

<%= link_to "Create a new Worksp_ce", new_meeting_path %>
<!-- data-markers="<%#= @markers.to_json %>" -->

app/views/meetings/new.html.erb
<div class="new-meeting-main">
  <div class="new-meeting-form">
    <%= simple_form_for @meeting do |f| %>
      <div class="new-form-input">
        <%= f.input :title, label: "Name your workspace" %>
        <%= f.input :description, label: "What are you working on?" %>
        <%= f.input :date, as: :datetime %>
        <div class="search-line">
          <%= f.hidden_field :google_place_id %>
          <!-- Automcomplete.js injects Google autocomplete here -->
          <%= f.input :location, label: "Select location or enter address", input_html: { id: 'meeting-address'} %>
        </div>
      </div>
      <div class="form-tab">
        <%= f.button :submit, 'Create new workspace', class: 'form-submit-btn'%>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="meeting-container">
  <div class="meeting">
    <div class="meeting-info">
      <div class="meeting-details">
        <h5><%= @meeting.location %></h5>
        <p> <%= @meeting.date %></p>
        <p><%= @meeting.description %></p>
        <p>Hosted by <%= @meeting.owner.first_name %> <%= @meeting.owner.last_name %></p>
          <div class="host-card">
            <div class="host-card-info">
              <img src="https://img.discogs.com/J0dDznbRdLgNsWDDktbsC0xCFRA=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3649743-1338847217-5371.jpeg.jpg" alt="" class="host-card-image">
              <h6><%= @meeting.owner.profession %></h6>
            </div>
          </div>
      </div>
      <div class="workspace-avatars">
        <h6>Attending:</h6>
        <ul>
          <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
          <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
          <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
          <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
        </ul>
      </div>
      <div class="meeting-actions">
        <% if policy(@meeting).update? && policy(@meeting).destroy? %>
          <%= link_to "Edit this meeting", edit_meeting_path(@meeting), class: 'button-wrk' %>
          <%= link_to "Delete this meeting", meeting_path, method: :delete, class: 'button-wrk' %>
        <% else %>
          <div id="new-attendance-render">
            <% if @current_meeting.empty? %>
              <%= link_to "Request to join this worksp_ce", new_meeting_attendee_path(@meeting), remote: true %> <br>
            <% else %>
              <h6>Request sent</h6>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="meeting-map">
    <div class="show-map-container">
      <div id="map"
        style="width: 100%;
        height: 500px;
        align-self: flex-start;"
        data-markers="<%= @marker.to_json %>"
        ></div>
    </div>
  </div>
</div>

app/views/pages/_hosting.html.erb
<% if current_user.hosted_meetings.length > 0 %>
  <h5>Your workspaces</h5>
  <div class="meeting-list-container hosting-grid">
    <% current_user.hosted_meetings.each do |meeting|  %>
      <div class="workspace-card">
        <span id="count"><%= meeting.attendees.where(confirmed: true).count %></span>
        <!-- <img src="https://source.unsplash.com/featured/?workspace" alt="cover-image" class="workspace-image"> -->
        <div class="workspace-avatars">
          <ul>
            <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
            <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
            <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
            <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
            <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
            <li><img src="https://www.jackholdsworth.com/profile.png" alt=""></li>
          </ul>
        </div>
        <div class="workspace-card-info">
          <h6><%= meeting.dateFormat %></h6>
          <h6><%= link_to meeting.location, meeting_path(meeting) %></h6>
        </div>
      </div>
    <% end %>
  </div>
  <h5>Workspaces you're attending:</h5>
  <div class="meeting-list-container sent-grid">
    <% @pending_requests.confirmed.each do |request| %>
      <div class="request-card">
        <div class="request-body">
          <img src="https://www.jackholdsworth.com/profile.png" alt="" class="">
          <div id="" class="request-info">
            <p><%#= request.meeting.dateFormat %></p>
            <p>Hosted by: <%= request.meeting.owner.username  %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h5><%= link_to "Create a new workspace", new_meeting_path  %></h5>
<% end %>

app/views/pages/_info_window.html.erb
<h6><%= link_to meeting.title, meeting_path(meeting) %></h6>

app/views/pages/_requested.html.erb
<% if @received_requests.empty? %>
  <h5>No requests yet!</h5>
<% else %>
  <h5>Requests to join your workspaces</h5>
  <div class="meeting-list-container requested-grid">
    <% @received_requests.reverse.each do |request| %>
      <div id="request" class="request-card">
        <div class="request-body">
          <img src="https://www.jackholdsworth.com/profile.png" alt="" class="">
          <div class="request-info">
            <p><%= request.meeting.location %></p>
            <p><%= request.message %></p>
          </div>
          <div class="request-card-actions">
            <p><%= link_to "Accept", meeting_attendee_path(request.meeting, request, attendee: { confirmed: true}), method: 'put', remote: true %></p>
            <p><%= link_to "Decline", meeting_attendee_path(request.meeting, request, attendee: { declined: true}), method: 'put', remote: true %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/_sent.html.erb
<% if @pending_requests.empty? %>
  <h5><%= link_to "Search for a Workspace", meetings_path %></h5>
<% else %>

  <h5>Your sent requests:</h5>
  <div class="meeting-list-container sent-grid">
    <% @pending_requests.awaiting.reverse.each do |request| %>
      <div class="request-card">
        <div class="request-body">
          <!-- <img src="https://www.jackholdsworth.com/profile.png" alt="" class=""> -->
          <div id="" class="request-info">
            <p class="item" ><%= link_to request.meeting.title, meeting_path(request.meeting) %></p>
            <p class="item"><%= request.meeting.date %></p>
            <p class= "item">Hosted by: <%= request.meeting.owner.username  %></p>
            <% if request.declined == false %>
              <p class="item">Status: Pending</p>
            <% else %>
              <p class="item">Status: Declined</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/_tabs.html.erb
<button id="hosting-tab"  data-content="hosting" class="tablinks">Hosting <%= current_user.hosted_meetings.count if @current_user.hosted_meetings.length > 0  %></button>
<button id="received-tab"  data-content="received" class="tablinks">Requests <%= @received_requests.count if @received_requests.length > 0  %></button>
<button id="sent-tab" data-content="sent" class="tablinks">Sent <%= @pending_requests.count if @pending_requests.length > 0  %></button>

app/views/pages/dashboard.html.erb
<div class="dash-container">
  <div class="self-container">
    <div class="user-card">
      <div class="user-card-info">
      <img src="https://img.discogs.com/J0dDznbRdLgNsWDDktbsC0xCFRA=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3649743-1338847217-5371.jpeg.jpg" alt="" class="user-card-image">
      <h6><%= current_user.first_name %></h6>
      <h6><%= current_user.profession %></h6>
      </div>
      <div class="user-card-bio">
        <p><%= current_user.bio %></p>
      </div>
      <div class="divider-line"></div>
      <div class="user-card-actions">
        <%= link_to 'Edit profile', edit_user_registration_path %>
      </div>
    </div>
  </div>
  <div class="dash-info-container">

    <div class="tab-select">
      <%= render '/pages/tabs' %>
    </div>

    <div id="hosting" class="tab-content hosting-render">
      <%= render '/pages/hosting' %>
    </div>
    <div id="received" class="tab-content requested-render">
      <%= render '/pages/requested' %>
    </div>
    <div id="sent" class="tab-content sent-render">
      <%= render '/pages/sent' %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-main">
  <div class="landing-container">
    <div class="home-cta">
      <h1>Worksp_ce</h1>
      <h4>Connect with remote workers near you</h4>
      <div class="cta-actions">
        <% if user_signed_in? %>
          <%= link_to "Create a new meeting", new_meeting_path %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </div>
    </div>

    <div
      id="map"
      style="width: 40%;
      height: 560px;"
      data-markers="<%= @markers.to_json %>"
    ></div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <nav>
    <h5><%= link_to "worksp_ce", root_path, class: 'nav-logo' %></h5>
    <h5><%= link_to "Dashboard", dashboard_path, "data-turbolinks" => "false" %></h5>
    <!-- <ul>
      <h5><li><%#= link_to "worksp_ce", root_path %></li></h5>
      <h5><li><a href="">About</a></li></h5>
      <h5><li><a href="">Search</a></li></h5>
    </ul> -->
  </nav>

app/views/users/show.html.erb
<div class="profile-container">
  <div class="profile-half">
    <h3>hi</h3>
  </div>
  <div class="user-meetings-half">
    <h3>also hi</h3>
  </div>
</div>